package pe.edu.ulima.services

import pe.edu.ulima.models.Imagen

class ImagenService {
    companion object {
        fun fetchAll(): List<Imagen> {
            return listOf(
                Imagen(0, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/427.png", 6),
                Imagen(1, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/414.png", 4),
                Imagen(2, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/441.png", 1),
                Imagen(3, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/211.png", 4),
                Imagen(4, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/239.png", 8),
                Imagen(5, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/74.png", 3),
                Imagen(6, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/588.png", 2),
                Imagen(7, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/773.png", 4),
                Imagen(8, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/621.png", 10),
                Imagen(9, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/458.png", 8),
                Imagen(10, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/596.png", 2),
                Imagen(11, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/720.png", 8),
                Imagen(12, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/334.png", 1),
                Imagen(13, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/15.png", 10),
                Imagen(14, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/292.png", 3),
                Imagen(15, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/233.png", 2),
                Imagen(16, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/491.png", 8),
                Imagen(17, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/704.png", 3),
                Imagen(18, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/271.png", 8),
                Imagen(19, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/18.png", 9),
                Imagen(20, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/154.png", 10),
                Imagen(21, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/282.png", 10),
                Imagen(22, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/232.png", 8),
                Imagen(23, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/661.png", 8),
                Imagen(24, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/192.png", 3),
                Imagen(25, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/176.png", 5),
                Imagen(26, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/461.png", 5),
                Imagen(27, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/197.png", 5),
                Imagen(28, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/203.png", 3),
                Imagen(29, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/476.png", 6),
                Imagen(30, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/365.png", 2),
                Imagen(31, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/191.png", 7),
                Imagen(32, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/751.png", 5),
                Imagen(33, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/790.png", 4),
                Imagen(34, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/35.png", 6),
                Imagen(35, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/577.png", 8),
                Imagen(36, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/122.png", 6),
                Imagen(37, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/648.png", 1),
                Imagen(38, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/496.png", 3),
                Imagen(39, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/561.png", 1),
                Imagen(40, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/747.png", 4),
                Imagen(41, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/185.png", 9),
                Imagen(42, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/394.png", 2),
                Imagen(43, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/71.png", 4),
                Imagen(44, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/162.png", 8),
                Imagen(45, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/660.png", 3),
                Imagen(46, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/122.png", 10),
                Imagen(47, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/559.png", 10),
                Imagen(48, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/703.png", 10),
                Imagen(49, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/636.png", 8),
                Imagen(50, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/792.png", 10),
                Imagen(51, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/548.png", 5),
                Imagen(52, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/204.png", 3),
                Imagen(53, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/335.png", 5),
                Imagen(54, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/411.png", 1),
                Imagen(55, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/320.png", 3),
                Imagen(56, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/448.png", 3),
                Imagen(57, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/661.png", 4),
                Imagen(58, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/602.png", 1),
                Imagen(59, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/532.png", 2),
                Imagen(60, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/258.png", 8),
                Imagen(61, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/46.png", 5),
                Imagen(62, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/465.png", 10),
                Imagen(63, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/227.png", 3),
                Imagen(64, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/608.png", 3),
                Imagen(65, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/321.png", 6),
                Imagen(66, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/140.png", 2),
                Imagen(67, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/610.png", 7),
                Imagen(68, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/612.png", 9),
                Imagen(69, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/750.png", 5),
                Imagen(70, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/377.png", 9),
                Imagen(71, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/166.png", 1),
                Imagen(72, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/246.png", 7),
                Imagen(73, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/796.png", 7),
                Imagen(74, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/309.png", 5),
                Imagen(75, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/432.png", 2),
                Imagen(76, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/24.png", 10),
                Imagen(77, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/633.png", 9),
                Imagen(78, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/655.png", 9),
                Imagen(79, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/648.png", 10),
                Imagen(80, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/785.png", 7),
                Imagen(81, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/515.png", 9),
                Imagen(82, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/411.png", 2),
                Imagen(83, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/686.png", 2),
                Imagen(84, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/710.png", 5),
                Imagen(85, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/584.png", 6),
                Imagen(86, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/82.png", 1),
                Imagen(87, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/249.png", 8),
                Imagen(88, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/302.png", 4),
                Imagen(89, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/445.png", 2),
                Imagen(90, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/66.png", 7),
                Imagen(91, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/295.png", 7),
                Imagen(92, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/94.png", 5),
                Imagen(93, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/189.png", 7),
                Imagen(94, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/26.png", 3),
                Imagen(95, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/190.png", 3),
                Imagen(96, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/471.png", 4),
                Imagen(97, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/636.png", 9),
                Imagen(98, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/304.png", 10),
                Imagen(99, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/442.png", 4),
                Imagen(100, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/607.png", 1),
                Imagen(101, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/632.png", 7),
                Imagen(102, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/680.png", 2),
                Imagen(103, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/375.png", 5),
                Imagen(104, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/261.png", 8),
                Imagen(105, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/196.png", 10),
                Imagen(106, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/3.png", 4),
                Imagen(107, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/444.png", 4),
                Imagen(108, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/299.png", 4),
                Imagen(109, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/403.png", 6),
                Imagen(110, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/268.png", 7),
                Imagen(111, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/173.png", 7),
                Imagen(112, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/64.png", 1),
                Imagen(113, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/76.png", 2),
                Imagen(114, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/602.png", 7),
                Imagen(115, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/253.png", 5),
                Imagen(116, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/573.png", 4),
                Imagen(117, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/470.png", 9),
                Imagen(118, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/692.png", 10),
                Imagen(119, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/715.png", 8),
                Imagen(120, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/376.png", 8),
                Imagen(121, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/514.png", 10),
                Imagen(122, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/794.png", 2),
                Imagen(123, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/116.png", 2),
                Imagen(124, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/382.png", 4),
                Imagen(125, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/542.png", 1),
                Imagen(126, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/67.png", 10),
                Imagen(127, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/393.png", 9),
                Imagen(128, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/634.png", 8),
                Imagen(129, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/61.png", 3),
                Imagen(130, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/180.png", 6),
                Imagen(131, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/639.png", 8),
                Imagen(132, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/225.png", 2),
                Imagen(133, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/225.png", 9),
                Imagen(134, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/653.png", 10),
                Imagen(135, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/187.png", 2),
                Imagen(136, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/758.png", 9),
                Imagen(137, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/259.png", 7),
                Imagen(138, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/382.png", 8),
                Imagen(139, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/563.png", 7),
                Imagen(140, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/91.png", 6),
                Imagen(141, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/719.png", 7),
                Imagen(142, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/150.png", 1),
                Imagen(143, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/778.png", 10),
                Imagen(144, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/713.png", 5),
                Imagen(145, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/355.png", 4),
                Imagen(146, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/28.png", 1),
                Imagen(147, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/262.png", 10),
                Imagen(148, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/522.png", 9),
                Imagen(149, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/3.png", 3),
                Imagen(150, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/23.png", 2),
                Imagen(151, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/75.png", 1),
                Imagen(152, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/216.png", 2),
                Imagen(153, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/524.png", 4),
                Imagen(154, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/691.png", 3),
                Imagen(155, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/13.png", 2),
                Imagen(156, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/398.png", 2),
                Imagen(157, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/275.png", 4),
                Imagen(158, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/728.png", 1),
                Imagen(159, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/792.png", 10),
                Imagen(160, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/488.png", 7),
                Imagen(161, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/233.png", 2),
                Imagen(162, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/502.png", 5),
                Imagen(163, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/512.png", 9),
                Imagen(164, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/803.png", 1),
                Imagen(165, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/702.png", 1),
                Imagen(166, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/176.png", 10),
                Imagen(167, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/482.png", 7),
                Imagen(168, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/121.png", 1),
                Imagen(169, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/252.png", 7),
                Imagen(170, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/600.png", 4),
                Imagen(171, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/246.png", 10),
                Imagen(172, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/489.png", 6),
                Imagen(173, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/164.png", 6),
                Imagen(174, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/177.png", 1),
                Imagen(175, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/214.png", 3),
                Imagen(176, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/770.png", 5),
                Imagen(177, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/32.png", 10),
                Imagen(178, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/507.png", 9),
                Imagen(179, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/607.png", 2),
                Imagen(180, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/631.png", 5),
                Imagen(181, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/572.png", 5),
                Imagen(182, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/796.png", 2),
                Imagen(183, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/169.png", 3),
                Imagen(184, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/131.png", 6),
                Imagen(185, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/750.png", 5),
                Imagen(186, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/726.png", 5),
                Imagen(187, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/574.png", 3),
                Imagen(188, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/656.png", 3),
                Imagen(189, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/784.png", 10),
                Imagen(190, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/268.png", 1),
                Imagen(191, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/85.png", 10),
                Imagen(192, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/404.png", 5),
                Imagen(193, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/273.png", 2),
                Imagen(194, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/774.png", 5),
                Imagen(195, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/620.png", 7),
                Imagen(196, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/58.png", 3),
                Imagen(197, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/514.png", 8),
                Imagen(198, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/408.png", 3),
                Imagen(199, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/251.png", 9),
            )
        }

        fun fetchByUserId(userId: Int): List<Imagen>{
            val respuesta : MutableList<Imagen> = arrayListOf()
            val list: List<Imagen> = fetchAll()
            for(imagen in list){
                if(imagen.usuarioId == userId){
                    respuesta.add(imagen)
                }
            }
            return respuesta
        }


        fun fetchImageByUserId(userId: Int): List<String>{
            val respuesta : MutableList<String> = arrayListOf()
            val list: List<Imagen> = fetchAll()
            for(imagen in list){
                if(imagen.id == userId){
                    respuesta.add(imagen.url)
                }
            }
            return respuesta
        }







    }
}